# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from smart_city/WeatherStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class WeatherStatus(genpy.Message):
  _md5sum = "5057a82170bb6f01299019173b4603ab"
  _type = "smart_city/WeatherStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string condition
float64 temperature

float32 temperature_in_celsius
string weather_description

"""
  __slots__ = ['condition','temperature','temperature_in_celsius','weather_description']
  _slot_types = ['string','float64','float32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       condition,temperature,temperature_in_celsius,weather_description

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WeatherStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.condition is None:
        self.condition = ''
      if self.temperature is None:
        self.temperature = 0.
      if self.temperature_in_celsius is None:
        self.temperature_in_celsius = 0.
      if self.weather_description is None:
        self.weather_description = ''
    else:
      self.condition = ''
      self.temperature = 0.
      self.temperature_in_celsius = 0.
      self.weather_description = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.condition
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_df().pack(_x.temperature, _x.temperature_in_celsius))
      _x = self.weather_description
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.condition = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.condition = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.temperature, _x.temperature_in_celsius,) = _get_struct_df().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.weather_description = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.weather_description = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.condition
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_df().pack(_x.temperature, _x.temperature_in_celsius))
      _x = self.weather_description
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.condition = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.condition = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.temperature, _x.temperature_in_celsius,) = _get_struct_df().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.weather_description = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.weather_description = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_df = None
def _get_struct_df():
    global _struct_df
    if _struct_df is None:
        _struct_df = struct.Struct("<df")
    return _struct_df
