// Generated by gencpp from file smart_city/WeatherServiceRequest.msg
// DO NOT EDIT!


#ifndef SMART_CITY_MESSAGE_WEATHERSERVICEREQUEST_H
#define SMART_CITY_MESSAGE_WEATHERSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smart_city
{
template <class ContainerAllocator>
struct WeatherServiceRequest_
{
  typedef WeatherServiceRequest_<ContainerAllocator> Type;

  WeatherServiceRequest_()
    : city_name()
    , latitude(0.0)
    , longitude(0.0)  {
    }
  WeatherServiceRequest_(const ContainerAllocator& _alloc)
    : city_name(_alloc)
    , latitude(0.0)
    , longitude(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _city_name_type;
  _city_name_type city_name;

   typedef float _latitude_type;
  _latitude_type latitude;

   typedef float _longitude_type;
  _longitude_type longitude;





  typedef boost::shared_ptr< ::smart_city::WeatherServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smart_city::WeatherServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WeatherServiceRequest_

typedef ::smart_city::WeatherServiceRequest_<std::allocator<void> > WeatherServiceRequest;

typedef boost::shared_ptr< ::smart_city::WeatherServiceRequest > WeatherServiceRequestPtr;
typedef boost::shared_ptr< ::smart_city::WeatherServiceRequest const> WeatherServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smart_city::WeatherServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smart_city::WeatherServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smart_city::WeatherServiceRequest_<ContainerAllocator1> & lhs, const ::smart_city::WeatherServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.city_name == rhs.city_name &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smart_city::WeatherServiceRequest_<ContainerAllocator1> & lhs, const ::smart_city::WeatherServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smart_city

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smart_city::WeatherServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smart_city::WeatherServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_city::WeatherServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_city::WeatherServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_city::WeatherServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_city::WeatherServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smart_city::WeatherServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19957a6673e039244d7d5f5f51f269a0";
  }

  static const char* value(const ::smart_city::WeatherServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19957a6673e03924ULL;
  static const uint64_t static_value2 = 0x4d7d5f5f51f269a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::smart_city::WeatherServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smart_city/WeatherServiceRequest";
  }

  static const char* value(const ::smart_city::WeatherServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smart_city::WeatherServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string city_name\n"
"float32 latitude\n"
"float32 longitude\n"
;
  }

  static const char* value(const ::smart_city::WeatherServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smart_city::WeatherServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.city_name);
      stream.next(m.latitude);
      stream.next(m.longitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WeatherServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smart_city::WeatherServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smart_city::WeatherServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "city_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.city_name);
    s << indent << "latitude: ";
    Printer<float>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<float>::stream(s, indent + "  ", v.longitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMART_CITY_MESSAGE_WEATHERSERVICEREQUEST_H
