// Generated by gencpp from file smart_city/WeatherServiceResponse.msg
// DO NOT EDIT!


#ifndef SMART_CITY_MESSAGE_WEATHERSERVICERESPONSE_H
#define SMART_CITY_MESSAGE_WEATHERSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <smart_city/WeatherStatus.h>

namespace smart_city
{
template <class ContainerAllocator>
struct WeatherServiceResponse_
{
  typedef WeatherServiceResponse_<ContainerAllocator> Type;

  WeatherServiceResponse_()
    : weather()  {
    }
  WeatherServiceResponse_(const ContainerAllocator& _alloc)
    : weather(_alloc)  {
  (void)_alloc;
    }



   typedef  ::smart_city::WeatherStatus_<ContainerAllocator>  _weather_type;
  _weather_type weather;





  typedef boost::shared_ptr< ::smart_city::WeatherServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smart_city::WeatherServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WeatherServiceResponse_

typedef ::smart_city::WeatherServiceResponse_<std::allocator<void> > WeatherServiceResponse;

typedef boost::shared_ptr< ::smart_city::WeatherServiceResponse > WeatherServiceResponsePtr;
typedef boost::shared_ptr< ::smart_city::WeatherServiceResponse const> WeatherServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smart_city::WeatherServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smart_city::WeatherServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smart_city::WeatherServiceResponse_<ContainerAllocator1> & lhs, const ::smart_city::WeatherServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.weather == rhs.weather;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smart_city::WeatherServiceResponse_<ContainerAllocator1> & lhs, const ::smart_city::WeatherServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smart_city

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smart_city::WeatherServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smart_city::WeatherServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_city::WeatherServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_city::WeatherServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_city::WeatherServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_city::WeatherServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smart_city::WeatherServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "653be75df0546fc1019bb908c6fde669";
  }

  static const char* value(const ::smart_city::WeatherServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x653be75df0546fc1ULL;
  static const uint64_t static_value2 = 0x019bb908c6fde669ULL;
};

template<class ContainerAllocator>
struct DataType< ::smart_city::WeatherServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smart_city/WeatherServiceResponse";
  }

  static const char* value(const ::smart_city::WeatherServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smart_city::WeatherServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smart_city/WeatherStatus weather\n"
"\n"
"\n"
"================================================================================\n"
"MSG: smart_city/WeatherStatus\n"
"string condition\n"
"float64 temperature\n"
;
  }

  static const char* value(const ::smart_city::WeatherServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smart_city::WeatherServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.weather);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WeatherServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smart_city::WeatherServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smart_city::WeatherServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "weather: ";
    s << std::endl;
    Printer< ::smart_city::WeatherStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.weather);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMART_CITY_MESSAGE_WEATHERSERVICERESPONSE_H
