// Generated by gencpp from file smart_city/WeatherServiceResponse.msg
// DO NOT EDIT!


#ifndef SMART_CITY_MESSAGE_WEATHERSERVICERESPONSE_H
#define SMART_CITY_MESSAGE_WEATHERSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smart_city
{
template <class ContainerAllocator>
struct WeatherServiceResponse_
{
  typedef WeatherServiceResponse_<ContainerAllocator> Type;

  WeatherServiceResponse_()
    : city_name()
    , weather_status()
    , temperature(0.0)  {
    }
  WeatherServiceResponse_(const ContainerAllocator& _alloc)
    : city_name(_alloc)
    , weather_status(_alloc)
    , temperature(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _city_name_type;
  _city_name_type city_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _weather_status_type;
  _weather_status_type weather_status;

   typedef float _temperature_type;
  _temperature_type temperature;





  typedef boost::shared_ptr< ::smart_city::WeatherServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smart_city::WeatherServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WeatherServiceResponse_

typedef ::smart_city::WeatherServiceResponse_<std::allocator<void> > WeatherServiceResponse;

typedef boost::shared_ptr< ::smart_city::WeatherServiceResponse > WeatherServiceResponsePtr;
typedef boost::shared_ptr< ::smart_city::WeatherServiceResponse const> WeatherServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smart_city::WeatherServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smart_city::WeatherServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smart_city::WeatherServiceResponse_<ContainerAllocator1> & lhs, const ::smart_city::WeatherServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.city_name == rhs.city_name &&
    lhs.weather_status == rhs.weather_status &&
    lhs.temperature == rhs.temperature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smart_city::WeatherServiceResponse_<ContainerAllocator1> & lhs, const ::smart_city::WeatherServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smart_city

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smart_city::WeatherServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smart_city::WeatherServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_city::WeatherServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_city::WeatherServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_city::WeatherServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_city::WeatherServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smart_city::WeatherServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8a808d2c751ef9193646ddc8af30499";
  }

  static const char* value(const ::smart_city::WeatherServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8a808d2c751ef91ULL;
  static const uint64_t static_value2 = 0x93646ddc8af30499ULL;
};

template<class ContainerAllocator>
struct DataType< ::smart_city::WeatherServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smart_city/WeatherServiceResponse";
  }

  static const char* value(const ::smart_city::WeatherServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smart_city::WeatherServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string city_name\n"
"string weather_status\n"
"float32 temperature\n"
"\n"
;
  }

  static const char* value(const ::smart_city::WeatherServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smart_city::WeatherServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.city_name);
      stream.next(m.weather_status);
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WeatherServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smart_city::WeatherServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smart_city::WeatherServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "city_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.city_name);
    s << indent << "weather_status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.weather_status);
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMART_CITY_MESSAGE_WEATHERSERVICERESPONSE_H
