// Generated by gencpp from file smart_city/WeatherService.msg
// DO NOT EDIT!


#ifndef SMART_CITY_MESSAGE_WEATHERSERVICE_H
#define SMART_CITY_MESSAGE_WEATHERSERVICE_H

#include <ros/service_traits.h>


#include <smart_city/WeatherServiceRequest.h>
#include <smart_city/WeatherServiceResponse.h>


namespace smart_city
{

struct WeatherService
{

typedef WeatherServiceRequest Request;
typedef WeatherServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WeatherService
} // namespace smart_city


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::smart_city::WeatherService > {
  static const char* value()
  {
    return "ec5c854fe33b5ba3e765055cce88be4e";
  }

  static const char* value(const ::smart_city::WeatherService&) { return value(); }
};

template<>
struct DataType< ::smart_city::WeatherService > {
  static const char* value()
  {
    return "smart_city/WeatherService";
  }

  static const char* value(const ::smart_city::WeatherService&) { return value(); }
};


// service_traits::MD5Sum< ::smart_city::WeatherServiceRequest> should match
// service_traits::MD5Sum< ::smart_city::WeatherService >
template<>
struct MD5Sum< ::smart_city::WeatherServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::smart_city::WeatherService >::value();
  }
  static const char* value(const ::smart_city::WeatherServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::smart_city::WeatherServiceRequest> should match
// service_traits::DataType< ::smart_city::WeatherService >
template<>
struct DataType< ::smart_city::WeatherServiceRequest>
{
  static const char* value()
  {
    return DataType< ::smart_city::WeatherService >::value();
  }
  static const char* value(const ::smart_city::WeatherServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::smart_city::WeatherServiceResponse> should match
// service_traits::MD5Sum< ::smart_city::WeatherService >
template<>
struct MD5Sum< ::smart_city::WeatherServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::smart_city::WeatherService >::value();
  }
  static const char* value(const ::smart_city::WeatherServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::smart_city::WeatherServiceResponse> should match
// service_traits::DataType< ::smart_city::WeatherService >
template<>
struct DataType< ::smart_city::WeatherServiceResponse>
{
  static const char* value()
  {
    return DataType< ::smart_city::WeatherService >::value();
  }
  static const char* value(const ::smart_city::WeatherServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SMART_CITY_MESSAGE_WEATHERSERVICE_H
