// Generated by gencpp from file homework_4/OddEvenCheck.msg
// DO NOT EDIT!


#ifndef HOMEWORK_4_MESSAGE_ODDEVENCHECK_H
#define HOMEWORK_4_MESSAGE_ODDEVENCHECK_H

#include <ros/service_traits.h>


#include <homework_4/OddEvenCheckRequest.h>
#include <homework_4/OddEvenCheckResponse.h>


namespace homework_4
{

struct OddEvenCheck
{

typedef OddEvenCheckRequest Request;
typedef OddEvenCheckResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OddEvenCheck
} // namespace homework_4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::homework_4::OddEvenCheck > {
  static const char* value()
  {
    return "4ff0b0ab1ed04611e3a2b4090af9ee4f";
  }

  static const char* value(const ::homework_4::OddEvenCheck&) { return value(); }
};

template<>
struct DataType< ::homework_4::OddEvenCheck > {
  static const char* value()
  {
    return "homework_4/OddEvenCheck";
  }

  static const char* value(const ::homework_4::OddEvenCheck&) { return value(); }
};


// service_traits::MD5Sum< ::homework_4::OddEvenCheckRequest> should match
// service_traits::MD5Sum< ::homework_4::OddEvenCheck >
template<>
struct MD5Sum< ::homework_4::OddEvenCheckRequest>
{
  static const char* value()
  {
    return MD5Sum< ::homework_4::OddEvenCheck >::value();
  }
  static const char* value(const ::homework_4::OddEvenCheckRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::homework_4::OddEvenCheckRequest> should match
// service_traits::DataType< ::homework_4::OddEvenCheck >
template<>
struct DataType< ::homework_4::OddEvenCheckRequest>
{
  static const char* value()
  {
    return DataType< ::homework_4::OddEvenCheck >::value();
  }
  static const char* value(const ::homework_4::OddEvenCheckRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::homework_4::OddEvenCheckResponse> should match
// service_traits::MD5Sum< ::homework_4::OddEvenCheck >
template<>
struct MD5Sum< ::homework_4::OddEvenCheckResponse>
{
  static const char* value()
  {
    return MD5Sum< ::homework_4::OddEvenCheck >::value();
  }
  static const char* value(const ::homework_4::OddEvenCheckResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::homework_4::OddEvenCheckResponse> should match
// service_traits::DataType< ::homework_4::OddEvenCheck >
template<>
struct DataType< ::homework_4::OddEvenCheckResponse>
{
  static const char* value()
  {
    return DataType< ::homework_4::OddEvenCheck >::value();
  }
  static const char* value(const ::homework_4::OddEvenCheckResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HOMEWORK_4_MESSAGE_ODDEVENCHECK_H
